name: bench

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install libasound2-dev
      run: sudo apt-get install -y libasound2-dev
    - uses: actions/checkout@v3
    - name: Install nightly toolchain
      run: rustup toolchain install nightly
    - name: Run bench
      run: cargo +nightly bench
